// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MyContext$ReactHooksTemplate = require("./MyContext.bs.js");

function Component2Nested(Props) {
  var greeting = Props.greeting;
  var match = React.useContext(MyContext$ReactHooksTemplate.context);
  var match$1 = match[0][/* map */0];
  return React.createElement("div", undefined, greeting, match$1 !== undefined ? match$1[/* name */0] : "Nothing to be seen here");
}

var make = Component2Nested;

exports.make = make;
/* react Not a pure module */
