// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

function Component1(Props) {
  var list = Props.list;
  return React.createElement("div", undefined, $$Array.of_list(List.map((function (prim) {
                        return prim;
                      }), List.map((function (e) {
                            return e[/* name */0];
                          }), list))));
}

var bla = /* record */[/* name */"123"];

var foo = /* record */[/* name */"123"];

var foo2 = /* record */[/* name */"123"];

var make = Component1;

exports.bla = bla;
exports.foo = foo;
exports.foo2 = foo2;
exports.make = make;
/* react Not a pure module */
