// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Theme = require("react-uwp/Theme");
var Button = require("react-uwp/Button");

function ReactUwp$Theme$Theme(Props) {
  var theme = Props.theme;
  var style = Props.style;
  var children = Props.children;
  var tmp = { };
  if (theme !== undefined) {
    tmp.theme = Caml_option.valFromOption(theme);
  }
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  if (children !== undefined) {
    tmp.children = Caml_option.valFromOption(children);
  }
  return React.createElement(Theme.Theme, tmp);
}

var Theme$1 = /* module */[/* make */ReactUwp$Theme$Theme];

var Theme$2 = /* module */[/* Theme */Theme$1];

function ReactUwp$Button(Props) {
  var tooltip = Props.tooltip;
  var style = Props.style;
  var children = Props.children;
  var tmp = { };
  if (tooltip !== undefined) {
    tmp.tooltip = Caml_option.valFromOption(tooltip);
  }
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  if (children !== undefined) {
    tmp.children = Caml_option.valFromOption(children);
  }
  return React.createElement(Button.default, tmp);
}

var Button$1 = /* module */[/* make */ReactUwp$Button];

exports.Theme = Theme$2;
exports.Button = Button$1;
/* react Not a pure module */
