// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var ReactShallowRenderer = require("bs-react-test-renderer/src/ReactShallowRenderer.bs.js");
var Component1$ReactHooksTemplate = require("../src/Component1.bs.js");

Jest.describe("Component1", (function (param) {
        return Jest.test("renders", (function (param) {
                      var component = ReactShallowRenderer.renderWithRenderer(React.createElement(Component1$ReactHooksTemplate.make, {
                                list: /* :: */[
                                  /* record */[/* name */"string"],
                                  /* [] */0
                                ]
                              }));
                      return Jest.ExpectJs[/* toBeDefined */26](Jest.ExpectJs[/* expect */0](component));
                    }));
      }));

/*  Not a pure module */
